### ISSUE TITLE
Fails to build on 5.9.16-1-MANJARO

### ISSUE THREAD

**Issue by eduardosm** [FrescoLogic/FL2000#56]
```
FL2000/src/fl2000_surface.c: In function ‘fl2000_surface_pin_down’:
FL2000/src/fl2000_surface.c:109:28: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  109 |    down_read(&current->mm->mmap_sem);
      |                            ^~~~~~~~
      |                            mmap_base
FL2000/src/fl2000_surface.c:115:26: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  115 |    up_read(&current->mm->mmap_sem);
      |                          ^~~~~~~~
      |                          mmap_base
FL2000/src/fl2000_surface.c:129:27: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  129 |   down_read(&current->mm->mmap_sem);
      |                           ^~~~~~~~
      |                           mmap_base
FL2000/src/fl2000_surface.c:144:25: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  144 |   up_read(&current->mm->mmap_sem);
      |                         ^~~~~~~~
      |                         mmap_base
FL2000/src/fl2000_surface.c: In function ‘fl2000_surface_map’:
FL2000/src/fl2000_surface.c:228:28: error: too many arguments to function ‘vm_map_ram’
  228 |   surface->mapped_buffer = vm_map_ram(
      |                            ^~~~~~~~~~
In file included from FL2000/src/fl2000_include.h:30,
                 from FL2000/src/fl2000_surface.c:8:
./include/linux/vmalloc.h:91:14: note: declared here
   91 | extern void *vm_map_ram(struct page **pages, unsigned int count, int node);
      |              ^~~~~~~~~~
```

**Comment by zeldin** [comment]
This is fixed by #67.

**Comment by catielanier** [comment]
> This is fixed by #67.

Can confirm, this branch builds on Garuda in `5.14.12-zen1-1-zen`.
